### ISSUE TITLE
Fehler bei Aufruf Detailseite

### ISSUE THREAD

**Issue by berecont** [plenta/contao-jobs-basic-bundle#103]
Contao 4.13.19
nach der Installation der Erweiterung [contao-image-alternatives](https://github.com/inspiredminds/contao-image-alternatives) erhalte ich beim Aufruf der Detailseite eines Jobs:
```Plenta\ContaoJobsBasic\GoogleForJobs\GoogleForJobs::__construct(): Argument #1 ($pictureFactory) must be of type Contao\CoreBundle\Image\PictureFactory, InspiredMinds\ContaoImageAlternatives\Image\PictureFactory given, called in /srv/www/intersport/public/chgsport/main/var/cache/dev/ContainerPGnqcX0/getGoogleForJobsService.php on line 22```

**Comment by ausi** [comment]
The [PictureFactoryInterface](https://github.com/contao/contao/blob/4.13/core-bundle/src/Image/PictureFactoryInterface.php) needs to be used here to fix this: https://github.com/plenta/contao-jobs-basic-bundle/blob/5b53bb28c82d52eb59ce4932d5ebe5fbc7653e05/src/Plenta/ContaoJobsBasic/GoogleForJobs/GoogleForJobs.php#L41
