### ISSUE TITLE
JobListing ignores the mapped Google Jobs employmentType value of custom employment types

### ISSUE THREAD

**Issue by jhdvc** [plenta/contao-jobs-basic-bundle#105]
When creating a custom employment type with the field "google_for_jobs_mapping" set to "FULL_TIME", the field employmentType in the JobListing JSON should display "FULL_TIME".

This seems to be broken in version 2, as employmentType is null for Postings with the custom employment type.

Tested with Version 2.4.1 and Contao Core 4.13.23.

**Comment by christianbarkowsky** [comment]
Fixed @jhdvc ... 2.4.2 released.
