### ISSUE TITLE
Individuelle Sortierung ermöglichen

### ISSUE THREAD

**Issue by OMOSde** [plenta/contao-jobs-basic-bundle#112]
Ein Kunde wünschte sich eine individuelle Sortierung der Stellenanzeigen in der Listenansicht.

Das konnte ich (fast) komplett updatesicher implementieren.

Ich habe das DCA auf Mode 5 (Tree) umgestellt, die Felder `pid` und `sorting` ergänzt und einen `paste_button_callback` im `sorting` ergänzt. Im DCA habe ich dann die Optionen für das Feld `` überschrieben.

Das einzige Problem ist die Methode `PlentaJobsBasicOfferModel.php::buildSearchQuery`. Hier stehen hardcodiert in Zeile 238 die Sortierfelder drin. Vielleicht kann man dies auch an die verfügbaren DCA-Optionen knüpfen.

Ist vielleicht für euch eine Überlegung wert.

**Comment by christianbarkowsky** [comment]
Wir kümmern uns @OMOSde

**Comment by veronikaplenta** [comment]
@OMOSde https://github.com/plenta/contao-jobs-basic-bundle/commit/617e6ba6afc0af619afe442b4252d591e657f30d das müsste dir so reichen, oder? Felder, bei denen `sorting`auf `true` steht, können sortiert werden.
