### ISSUE TITLE
Verwendung ohne Listen-Modul erzeugt foreach-Fehler

### ISSUE THREAD

**Issue by OMOSde** [plenta/contao-jobs-basic-bundle#116]
Hi,

wir setzen das Bundle ohne ein Modul des Typs `plenta_jobs_basic_offer_list` ein. Das führt in `/plenta/contao-jobs-basic-bundle/src/Plenta/ContaoJobsBasic/Contao/Model/PlentaJobsBasicOfferModel.php:145` zu einem foreach-Fehler.

Das ließe sich mit einer if-Abfrage beheben. Es ergibt sich dann ein Folgefehler in `vendor/plenta/contao-jobs-basic-bundle/src/Plenta/ContaoJobsBasic/Controller/Contao/FrontendModule/JobOfferReaderController.php:L199`, da der erlaubte Rückgabewert `null` nicht berücksichtigt wird.

**Comment by veronikaplenta** [comment]
@OMOSde Die Fehler habe ich in https://github.com/plenta/contao-jobs-basic-bundle/commit/d692518141e977fb766853f4669ff315cc874af1 behoben.
Wir sind uns aber unsicher, wie der Use Case in dem Fall ist. Wieso verwendest du das Bundle ohne Liste? Wenn wir im Model kein PageModel für die Stelle finden können, wird sie auch nicht in die Searchable Pages aufgenommen.

**Comment by OMOSde** [comment]
Hi, danke für die Antwort.

Ich habe in einem Rocksolid-Custom-Element per DCA eine Auswahl von Stellenanzeigen integriert. Damit kann ein Redakteur die Stellenanzeigen selbst gruppieren. Daher benötige ich das mitgelieferte Listen-Modul nicht.

Ich sehe das auch nicht zwingend als Fehler, sondern er als Verbesserung an.
