### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by mammut47** [plenta/contao-jobs-basic-bundle#121]
Es wäre schön, wenn überall die Templates wählbar wären.
So könnte pro Anzeige entschieden werden, wie die einzelnen Templates verwendet werden
Stellenanzeigen - Teasertext
Stellenanzeigen - Stellenbeschreibung
usw.

**Comment by christianbarkowsky** [comment]
Hey @mammut47 der Reader besteht aus einem ganzen Set von Templates `plenta_jobs_basic_reader_`* ... geht es dir um das Modul Template `mod_plenta_jobs_basic_offer_reader` oder um die Einzelteile?

**Comment by mammut47** [comment]
Mir geht es tatsächlich um die Einzelteile. Ich kann die Templates anlegen. Aber das gilt dann immer und überall. Ich kann nicht entscheiden, wann genau welche Vorlage gelten soll. Im Modul "Stellenanzeigen - Detailansicht" kann ich angeben, welches Modultemplate verwendet wird. Zusätzlich kann ich angeben, welche Template-Teile verwendet werden.
![grafik](https://github.com/plenta/contao-jobs-basic-bundle/assets/12047148/a7c52f19-b640-4be8-a7f8-4dddda4f1b52)
Ich kann aber für die Template-Teile nicht sagen, welches Template verwendet wird. 
Ich habe aber auch noch keine Idee, wie das im Modul eingestellt werden könnte, da es ja im Prinzip dynamisch ist. Je nachdem wie viele Template-Teile ich im Modul verwenden möchte.

**Comment by christianbarkowsky** [comment]
@mammut47 bitte melde dich hierzu bei uns >> [plenta.io](https://plenta.io)
