### ISSUE TITLE
Stellenanzeigen-Teaser

### ISSUE THREAD

**Issue by swinde** [plenta/contao-jobs-basic-bundle#126]
Verwendung des Elementtyps "Stellenanzeigen-Teaser" auf Startseite.

Ich verwende das Element um Stellenangebote anzuteasern. 
Jetzt gibt es aber keine aktiven Stellenangebote mehr. Das im Teaser eingestellte Stellenangebot wird aber weiterhin auf der Startseite ausgegeben. Ich hatte hier einen Hinweistext wie "Zur Zeit sind keine offenen Stellen zu besetzen." erwartet.

Vg Steffen Winde

**Comment by christianbarkowsky** [comment]
Danke für den Hinweis @swinde 
Bauen wir ein.

**Comment by christianbarkowsky** [comment]
Hey @swinde ist im Master. Passt wir das so?

**Comment by swinde** [comment]
Genau so habe ich mir das vorgestellt! Super!
