### ISSUE TITLE
Twig Templates in Contao 5.3.6?

### ISSUE THREAD

**Issue by Shoekrates** [plenta/contao-jobs-basic-bundle#138]
Hallo!
Nach einem Update auf Contao 5.3.6 und Plenta Jobs 3.0.8 greifen meine individuellen Anpassungen des Templates „plenta_jobs_basic_offer_default.html5“ nicht mehr.
Leider komme ich aktuell nicht dahinter, ob die Templates überhaupt schon komplett auf Twig umgestellt wurden. Ich kann zwar neue Templates im Backend von Contao anlegen, die sind aber bis auf die Extend-Zeile leer.
Hier im Repository sind im Ordner /Resources/Views zwar Twig-Templates, aber die helfen nicht weiter, noch entsprechen Sie der vorgeschlagenen Ordner-Struktur /forntend_module/ oder /content_element/.
Wie ist das aktuell geregelt und wie komme ich an die Template Parts, um meine Änderungen wieder einzubauen?

**Comment by Shoekrates** [comment]
Hallo. Ich möchte nach mehr als einem Monat nochmal nachfragen, ob sich hier irgendwelche Lösungen anbieten?

**Comment by christianbarkowsky** [comment]
Hey @Shoekrates wir haben dich nicht vergessen. Lust auf eine Teams-Session?

**Comment by Shoekrates** [comment]
Hallo @christianbarkowsky hatte dich auf deine Nachricht hier per Mail angeschrieben.

**Comment by christianbarkowsky** [comment]
Hey @Shoekrates ... mit einem HTML5 Tempalte kannst du kein TWIG Tempalte überschreiben.
Hier ist der Bauplan ... https://github.com/plenta/contao-jobs-basic-bundle/blob/3.0/contao/templates/_new/plenta_jobs_basic_offer_default.html.twig

Ich melde mich bei dir. ☎️

**Comment by Shoekrates** [comment]
Hallo @christianbarkowsky mit dem neuen Twig-Template habe ich das Markup wieder in den Zustand vor dem Contao 5 Update versetzen können. Vielen Dank an euch für die Ergänzung!
