### ISSUE TITLE
Fehler im Seiten-Routing durch Plugin

### ISSUE THREAD

**Issue by RobinSchwaiger** [plenta/contao-jobs-basic-bundle#141]
Wir haben in einem neuen Projekt leider das Problem, dass das Job-Plugin Fehler im Seitenrouting verursacht und Seiten aufrufbar und indexierbar sind, die es eigentlich nicht geben sollte, da die 404-Seite nicht mehr greift.

Beispiel: https://www.airlloyd.de/de/hubschrauber-rundfluege/hier-sollte-eine-404-seite-erscheinen

**Comment by veronikaplenta** [comment]
@RobinSchwaiger welche Version hast du installiert?

**Comment by fritzmg** [comment]
There are a few places in the extension where `Input::get('auto_item')` needs to be replaced with `Input::get('auto_item', false, true)`.

`Input::get('auto_item')` must _only_ be used in a reader module and never in any code that is potentially executed on every request.

**Comment by RobinSchwaiger** [comment]
> @RobinSchwaiger welche Version hast du installiert?

Version 2.4.12

**Comment by RobinSchwaiger** [comment]
> @RobinSchwaiger Neue Version ist getagged, probier mal, sollte damit passen. @fritzmg thanks for your input!

Wow, das ging schnell. Von solchem Support träumt man :)
Funktioniert wieder, danke!
