### ISSUE TITLE
Browser language overrides page language

### ISSUE THREAD

**Issue by MacKP** [plenta/contao-jobs-basic-bundle#151]
Moin moin,
einen hab ich noch gefunden. Wir haben bei unserer Installation ja recht spannende Dinge. Dabei ist es vorgekommen, dass man unter Umständen nicht die aktuelle Sprache im request hat. Das liegt anscheinend an Zeile 232 in PlentaJobsBasicOfferModel.php:
```
$language = $requestStack->getMainRequest()->getLocale();
```
Dadurch bekommt man die aktuelle Sprache vom Browser, was im Kontext dann falsch sein kann (Deutscher Seitenbaum, aber Browser ist auf engl. eingestellt).
Besser funktioniert hier:
```
$language = $requestStack->getCurrentRequest()->getLocale();
```
Dadurch bekommt man immer die Sprache vom aktuellen Seitenbaum :-)

Könnt ihr das auch noch bitte patchen?
Danke schon mal!

Viele Grüße
Marc

**Comment by veronikaplenta** [comment]
@MacKP Danke fürs Debuggen. :) Ich hab's an anderen Stellen auch gleich korrigiert. Bitte update mal, dann sollte es eigentlich alles funktionieren.

**Comment by MacKP** [comment]
@veronikaplenta das scheint super zu funktionieren ;-)
Danke für eure schnelle Hilfe!

Viele Grüße
