### ISSUE TITLE
Structured data in der Jobliste

### ISSUE THREAD

**Issue by cubex-hro** [plenta/contao-jobs-basic-bundle#41]
Moin, ich würde gerne in der Jobliste schon die Strukturierten Daten ausgeben

leider kann ich den GoogleForJobs service nicht laden weil dieser nicht auf public steht

entweder integriert man das direkt für das template plenta_jobs_basic_offer_default.html5 oder man setzt den container auf public dann könnte man sich überall wo ein jobOffer vorhanden ist die structured data generieren lassen

LG

**Comment by christianbarkowsky** [comment]
Google erlaubt ja nur einen Tag pro Seite ... wir stellen den Service aber gern auf **public**. @cubex-hro

**Comment by cubex-hro** [comment]
Vielen Dank.
