### ISSUE TITLE
Banner im Backend ausblenden

### ISSUE THREAD

**Issue by contaoacademy** [plenta/contao-jobs-basic-bundle#42]
Die blaue Infoleiste auf der Contao-Übersicht lenkt mich ab. Ich denke, es ist etwas Besonderes passiert, das meine Aufmerksamkeit braucht. Dabei ist es ja nur eine Info. Es wäre schön, wenn ich den Banner ausblenden und nur noch im Menüpunkt Einstellungen sehen kann.

Evtl. kann man das Banner auch wegklicken und es kommt dann erst nach 14 oder 30 Tagen wieder.

**Comment by christianbarkowsky** [comment]
Wir verschieben die Infoleiste. Du sollst nicht abgelenkt werden @contaoacademy 💋
