### ISSUE TITLE
Wrong Typs for Database Entrys

### ISSUE THREAD

**Issue by Eaglemong** [plenta/contao-jobs-basic-bundle#44]
Für "Bild Feld"
An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `contao`.`tl_plenta_jobs_basic_offer`.`addImage` at row 1

Für "Gehalt Feld"
Plenta\ContaoJobsBasic\Helper\NumberHelper::formatNumberFromDbForDCAField(): Argument #1 ($number) must be of type ?string, int given, called in /var/www/html/contao/vendor/plenta/contao-jobs-basic-bundle/src/Plenta/ContaoJobsBasic/EventListener/Contao/DCA/TlPlentaJobsBasicOffer.php on line 145

**Comment by veronikaplenta** [comment]
@christianbarkowsky https://github.com/contao/core-bundle/blob/4.13/src/Resources/contao/classes/Ajax.php#L452 Im Core wird beim AJAX-Request (beim Ausblenden der Subpalette) fest ein leerer String als false-Wert in die Datenbank eingetragen.

**Comment by christianbarkowsky** [comment]
Fixed @Eaglemong!

Thx for reporting the bug. Sorry fot the delay.
