### ISSUE TITLE
Invalid datetime format [exception]

### ISSUE THREAD

**Issue by Eaglemong** [plenta/contao-jobs-basic-bundle#45]
Hi Zusammen,

habe leider wieder eine Exception für euch. Datenbank Typen stimmen nicht überein wenn ich Stellenangebote kopieren möchte.

An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `contao`.`tl_plenta_jobs_basic_offer`.`published` at row 1

Generell sollten mal die DCA Formate geprüft werden für Datenbankeinträge.
Wir benutzen Version 4.13.5 von Contao.

Lg

**Comment by christianbarkowsky** [comment]
Fixed. @Eaglemong
