### ISSUE TITLE
On Contao 4.9 the news reader does not work anymore after installing contao-jobs-basic

### ISSUE THREAD

**Issue by heimseiten** [plenta/contao-jobs-basic-bundle#54]
Thank you for the great bundle!

Something went wrong in the ChangelanguageNavigationListener.php in Contao 4.9.

If i add 
`if ( $offerRepo->findPublishedByIdOrAlias($alias) ) {` 
before 
`$jobOffer = $offerRepo->findPublishedByIdOrAlias($alias);` 
and close the if statement behind 
`$event->getUrlParameterBag()->setUrlAttribute('items', $newAlias);` 
then the newsreader works again.

And to change the language from the fallback language to the not fallback language works. But not the other way.

Can you help?

**Comment by christianbarkowsky** [comment]
Hey @heimseiten ✌️ 
Please call me - the problem I have to see live.
