### ISSUE TITLE
Location is mandatory even if home office is the only option

### ISSUE THREAD

**Issue by kikmedia** [plenta/contao-jobs-basic-bundle#63]
First of all, thanks to you for the great extension.

I've stumbled into a logical glitch regarding the job location settings on Plenta Jobs (Basic) 1.4.4. I've tried to publish a job where remote should be the only option, but when I try to make approprioate settings, the location field is mandatory. IMHO, this is not correct, since the only way to circumvenct is publishing a remote-only job location, which is clearly not what I want.

![Bildschirmfoto 2022-10-04 um 10 02 19](https://user-images.githubusercontent.com/1022895/193766771-005ad373-e7b4-4740-be61-298b72f775e9.png)

**Comment by christianbarkowsky** [comment]
Hey @kikmedia,
thanks for the feedback and finding the bug. The error will be fixed.
