### ISSUE TITLE
Fehler beim Aufruf der Detailansicht

### ISSUE THREAD

**Issue by FrischBlau** [plenta/contao-jobs-basic-bundle#78]
Moin,
beim Aufruf der Detailansicht (via Link aus Stellenanzeige Liste oder direkter Aufruf) kommt ein Fehler. Das Log sagt:

request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "contao.routing.response_context_accessor"." at /html/contao4.9/vendor/symfony/dependency-injection/Container.php line 289 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"contao.routing.response_context_accessor\". at /html/contao4.9/vendor/symfony/dependency-injection/Container.php:289)"} 

Jobs Basic Bundle Version 2.0.2
Contao 4.9.37
PHP 7.4.33

**Comment by christianbarkowsky** [comment]
Hey @FrischBlau,

ups ... Jobs 2 ist für Contao 4.13 und höher.
Ich passe das noch an.

Sorry für den Fehler.

**Comment by FrischBlau** [comment]
Klappt leider noch nicht. Bei Neuinstallation wird unter 4.9 nur Version 2.02 installiert. Automatische Aktualisierung einer vorhandenen 2.0.2 schlägt fehl und wenn ich die 2.0.3 manuell einstelle, bricht die Installation ab mit
"plenta/contao-jobs-basic-bundle 2.0.3 requires contao/core-bundle ^4.13"
