### ISSUE TITLE
Remove Haste as dependency

### ISSUE THREAD

**Issue by veronikaplenta** [plenta/contao-jobs-basic-bundle#84]
Use Symfony forms instead of Haste forms

**Comment by Shoekrates** [comment]
Hi,
I can't install the Jobs bundle currently due to a Haste incompatibility (needs ^4.25), although Haste 5.0.16 is installed because of notification center 1.7.1 on PHP 8.1.
Will this be resolved through this Commit? When is it going to be avaliable?

**Comment by veronikaplenta** [comment]
Hi,
yes, this will solve the issue. I just created a new tag.

**Comment by Shoekrates** [comment]
Super, installation worked. Thanks!
