### ISSUE TITLE
Fehler beim Detailseiten-Aufruf von Sprachvarianten

### ISSUE THREAD

**Issue by chrismchn** [plenta/contao-jobs-basic-bundle#85]
[prod-2023-02-09.log](https://github.com/plenta/contao-jobs-basic-bundle/files/10706030/prod-2023-02-09.log)
Fehler kommt beim Aufruf der Detailansicht der Sprachversion - in diesem Fall EN. Listenansicht funktioniert aber.

**Comment by veronikaplenta** [comment]
@chrismchn Kannst du einmal den aktuellen Stand aus dem Master ziehen und gucken, ob es damit funktioniert?

**Comment by chrismchn** [comment]
Hallo,
es ist bereits die 2.2 installiert. ????

Ich bin erst am Montag wieder im Büro.
Grüße
Christian

veronikaplenta ***@***.***> schrieb am Fr. 10. Feb. 2023 um
11:03:
