### ISSUE TITLE
Filter: Absende-Button unnötig

### ISSUE THREAD

**Issue by k-webdesign** [plenta/contao-jobs-basic-bundle#92]
Der Button "Absende-Button hinzufügen" macht irgendwie keinen Sinn, da der Filter greift, sobald man eine Checkbox anhakt. Entweder sollte der Button generell rausgenommen werden. Oder das automatische Filtern sollte dann abgestellt werden, sodass der Button seine tatsächliche Berechtigung erhält.

**Comment by veronikaplenta** [comment]
@k-webdesign Wir lassen den Button da, da er gerade für Leute mit deaktiviertem JavaScript sinnvoll sein kann. Er kann aber ja in den Modul-Einstellungen deaktiviert werden.

**Comment by k-webdesign** [comment]
Okay. Wäre es aber für die Usability möglich, ihn tatsächlich nur bei deaktiviertem JS anzuzeigen? Wenn ich ihn in den Moduleinstellungen deaktiviere, ist er ja auch bei deaktiviertem JS weg.

**Comment by veronikaplenta** [comment]
@k-webdesign Wir haben uns intern besprochen und würden den Button gerne so lassen. Du kannst ja sonst das Template anpassen.
