### ISSUE TITLE
Listen-Template springt um, nachdem gefiltert wurde

### ISSUE THREAD

**Issue by k-webdesign** [plenta/contao-jobs-basic-bundle#94]
Ich habe ein angepasstes plenta_jobs_basic_offer_default.html5. Solange ich noch nicht filtere, ist alles gut. Mein eigenes Template wird genommen:
<img width="1687" alt="Bildschirm­foto 2023-03-15 um 12 17 53" src="https://user-images.githubusercontent.com/4130440/225293912-e624fc3e-5e54-4d16-bbe9-a1014dfcd3a2.png">

Aktivere ich dann aber den Filter, wird irgendwie wieder das Template aus vendor gezogen:
<img width="1702" alt="Bildschirm­foto 2023-03-15 um 12 18 16" src="https://user-images.githubusercontent.com/4130440/225293993-22319b63-7e43-4487-860e-dce0207d1100.png">

**Comment by veronikaplenta** [comment]
Doch kein Contao-Bug, sondern eine Interaktion mit Theme-Unterordnern.
@k-webdesign Falls du nicht mehrere Themes hast und für jedes Theme ein eigenes Template benötigst, könntest du als Zwischenlösung, bis du auf 4.13 updaten kannst, das Template direkt in den Templates-Ordner verschieben. Dann sollte es funktionieren.

**Comment by k-webdesign** [comment]
Habs eben im Slack gelesen, danke :)

**Comment by berecont** [comment]
Ich hänge mich hier ran - hatte hierzu auch gestern noch eine email an Christian gesendet. Hierin ist auch das aktuell betroffene Projekt vermerkt.
Contao 4.13.18 selbiges Verhalten
Das Verschieben des angepassten Templates plenta_jobs_basic_offer_default.hmtl5 in `/template `bringt Abhilfe.
Verbleibt das Template in `/template/theme/` dann greift der Filter falsch.

**Comment by veronikaplenta** [comment]
@berecont Ist jetzt gefixt, neue Version kommt bald
