### ISSUE TITLE
Unternehmen: Telefon + Mailadresse hinzufügen

### ISSUE THREAD

**Issue by k-webdesign** [plenta/contao-jobs-basic-bundle#95]
Es wäre sehr hilfreich, wenn beim Anlegen eines Standortes auch Felder für Telefon und Mailadresse verfügbar wären

**Comment by christianbarkowsky** [comment]
Es gibt nun Add-ons für das Jobs Basic Bundle @k-webdesign
https://plenta.io/contao-jobs-basic/add-ons
