### ISSUE TITLE
Filter + Templateanpassung greift nicht

### ISSUE THREAD

**Issue by berecont** [plenta/contao-jobs-basic-bundle#98]
`plenta_jobs_basic_offer_default.html5`
passe ich das Template an (in meinem Fall ein zusätzlicher Button) wird die Änderung im Frontend solange angezeigt, bis ich den Filter anwende. 

• Frontend wird mit Änderung angezeigt
• Ich setze den Filter » Filter wird angewandt » Änderungen im Template jedoch nicht
• Refresh Browser » Änderung im Template wird übernommen
• Filter wieder zurückgenommen » es erscheint wieder das plenta-Template
• Refresh Browser » Änderung im Template wird übernommen

Mit der Filterung wird wohl das plenta-Original-Template herangezogen und ein angepasstes Template aus dem /template/ Ordner wird bis zum Refresh des Browsers ignoriert.

**Comment by k-webdesign** [comment]
Hab ich in #94 schon gemeldet :)
