### ISSUE TITLE
Land wird nicht im Template ausgegeben

### ISSUE THREAD

**Issue by k-webdesign** [plenta/contao-jobs-basic-bundle#99]
Das Land wird nicht im Listentemplate ausgegeben, obwohl ich es im Standort per Dropdown eintrage

<img width="1069" alt="Bildschirm­foto 2023-03-27 um 14 26 15" src="https://user-images.githubusercontent.com/4130440/227942258-a0fc0ca5-dc3b-4796-abe5-d2c4b5660c96.png">

**Comment by k-webdesign** [comment]
Das Land müsste dann auch mit addressCountry versehen werden

**Comment by veronikaplenta** [comment]
@k-webdesign in der nächsten Version wird das Land mit in die Meta-Daten aufgenommen. Die Ausgabe muss dann aber über ein angepasstes Template erfolgen.
